- name: Disable nodejs default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable Nodejs 20 version
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Add expense user
  ansible.builtin.user:
    name: expense

- name: Copy backend service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: import app prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

- name: Download nodejs app dependencies
  community.general.npm:
    path: /app

- name: install mysql client and mysql python module
  ansible.builtin.dnf:
    name:
      - mysql
      - python3-PyMySQL
    state: present

# name: load schema
#community.mysql.mysql_db:
# state: import
#name: all
#target: /app/schema/backend.sql
#login_user: mysql_username
#login_password: mysql_password
#login_host: mysql-{{env}}.poodevops.online

- name: load schema
  ansible.builtin.shell: mysql -h mysql-{{env}}.poodevops.online -uroot -pExpenseApp@1 < /app/schema/backend.sql

- name: start backend service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: true