- name: Installing mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Start mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: set root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secret.mysql_password }}
  ignore_errors: yes