- name: Installing mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name:  install hvac
  ansible.builtin.shell: |
    pip3.9 install hvac
    pip3.11 install hvac    

- name: Start mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: set root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.mysql_password }}
  ignore_errors: yes