component: backend
app_path: /app
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=expense-{{env}}/data/backend token={{vault_token}} url=https://vault-internal.rdevopsb79.online:8200 validate_certs=false') }}"
app_user: expense