- name: Delete existing application directory
  ansible.builtin.file:
    name: "{{ app_path }}"
    state: absent

- name: create application directory
  ansible.builtin.file:
    name: "{{ app_path }}"
    state: directory
    owner: "{{app_user}}"
    group: "{{app_user}}"

- name: Download & extract {{ component }} code
  ansible.builtin.unarchive:
    src:  https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ app_path }}"
    remote_src: true
    owner: "{{app_user}}"
    group: "{{app_user}}"